#!/usr/bin/env bash
# 운영 EC2에 M2-08 Nginx와 TLS 구성을 설치한다. 재실행해도 결과가 같다.
#
# 저장소 파일을 인스턴스로 옮긴 스테이징 디렉터리를 인자로 받는다.
# 스테이징에는 다음 파일이 있어야 한다.
#   nginx.conf  masiton.click.conf  00-masiton-upgrade-map.conf
#   masiton-tls-renew.service  masiton-tls-renew.timer  tls-deploy-cert.sh  nginx-smoke.sh
#
# 사용: sudo ./nginx-install.sh [스테이징 디렉터리]
set -euo pipefail

STAGE="${1:-/tmp/masiton-deploy}"
OPT_DIR=/opt/masiton
DEPLOYMENT_ENV_FILE="${DEPLOYMENT_ENV_FILE:-/etc/masiton/deployment.env}"
if [ -f "$DEPLOYMENT_ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$DEPLOYMENT_ENV_FILE"
  set +a
fi

for f in nginx.conf masiton.click.conf 00-masiton-upgrade-map.conf \
         masiton-tls-renew.service masiton-tls-renew.timer tls-deploy-cert.sh nginx-smoke.sh; do
  [ -f "$STAGE/$f" ] || { echo "스테이징에 $f 가 없다: $STAGE" >&2; exit 1; }
done

if ! command -v nginx >/dev/null 2>&1; then
  dnf install -y nginx >/dev/null
fi
echo "nginx: $(nginx -v 2>&1)"

install -d -m 0755 "$OPT_DIR/bin"
install -m 0750 "$STAGE/tls-deploy-cert.sh" "$OPT_DIR/bin/tls-deploy-cert.sh"

SITE_CONF=/etc/nginx/conf.d/masiton.click.conf
UPGRADE_MAP_CONF=/etc/nginx/conf.d/00-masiton-upgrade-map.conf
NGINX_CONF=/etc/nginx/nginx.conf
REAL_IP_CONF=/etc/nginx/conf.d/10-masiton-real-ip.conf
BASIC_AUTH_DROPIN=/etc/systemd/system/nginx.service.d/10-masiton-basic-auth.conf
OLD_AUTH_MAP=/etc/nginx/conf.d/01-masiton-api-auth-map.conf

# Nginx와 백엔드가 함께 gate-free 릴리즈로 전환된다. 새 설정의 구문은
# 유효하지만 smoke가 실패하는 경우를 포함해, 설치 중 바꾼 Nginx 산출물을
# 직전 상태로 되돌릴 수 있어야 한다. 이전 설정이 검증 gate를 포함한
# 이 스크립트는 app-deploy의 rollback trap 안에서 실행된다. 구버전이면
# nginx-install의 Nginx 복구와 app-deploy의 paired app rollback이 함께 수행된다.
ROLLBACK_DIR=$(mktemp -d)
backup_or_ignore() {
  local source="$1" target="$2"
  if [ -f "$source" ]; then
    mkdir -p "$(dirname "$target")"
    cp -p "$source" "$target"
  fi
}
backup_or_ignore "$SITE_CONF" "$ROLLBACK_DIR/site.conf"
backup_or_ignore "$UPGRADE_MAP_CONF" "$ROLLBACK_DIR/upgrade-map.conf"
backup_or_ignore "$NGINX_CONF" "$ROLLBACK_DIR/nginx.conf"
backup_or_ignore "$REAL_IP_CONF" "$ROLLBACK_DIR/real-ip.conf"
backup_or_ignore "$BASIC_AUTH_DROPIN" "$ROLLBACK_DIR/basic-auth-dropin.conf"
backup_or_ignore "$OLD_AUTH_MAP" "$ROLLBACK_DIR/auth-map.conf"

restore_or_remove() {
  local backup="$1" target="$2"
  if [ -f "$backup" ]; then
    install -d "$(dirname "$target")"
    install -m 0644 "$backup" "$target"
  elif [ -e "$target" ] || [ -L "$target" ]; then
    rm -f "$target"
  fi
}

on_install_failure() {
  local status=$?
  trap - ERR
  echo "Nginx gate-free 전환에 실패했다. 직전 Nginx 구성을 복구한다." >&2
  restore_or_remove "$ROLLBACK_DIR/site.conf" "$SITE_CONF"
  restore_or_remove "$ROLLBACK_DIR/upgrade-map.conf" "$UPGRADE_MAP_CONF"
  restore_or_remove "$ROLLBACK_DIR/nginx.conf" "$NGINX_CONF"
  restore_or_remove "$ROLLBACK_DIR/real-ip.conf" "$REAL_IP_CONF"
  restore_or_remove "$ROLLBACK_DIR/basic-auth-dropin.conf" "$BASIC_AUTH_DROPIN"
  restore_or_remove "$ROLLBACK_DIR/auth-map.conf" "$OLD_AUTH_MAP"
  systemctl daemon-reload || true
  systemctl restart nginx || echo "Nginx 복구 후 재시작도 실패했다. paired rollback과 수동 복구가 필요하다." >&2
  rm -rf "$ROLLBACK_DIR"
  exit "$status"
}
trap on_install_failure ERR


# 인증서를 먼저 내려받아야 Nginx가 기동한다. ssl_certificate 파일이 없으면
# 설정 검사부터 실패한다.
AWS_REGION="${AWS_REGION:-ap-northeast-2}" "$OPT_DIR/bin/tls-deploy-cert.sh"

install -m 0644 "$STAGE/00-masiton-upgrade-map.conf" "$UPGRADE_MAP_CONF"
install -m 0644 "$STAGE/masiton.click.conf" "$SITE_CONF"
rm -f "$BASIC_AUTH_DROPIN" "$OLD_AUTH_MAP"

# 최상위 설정을 저장소 산출물로 교체한다. 배포판 기본 설정에는
# /usr/share/nginx/html을 서비스하는 server 블록이 있어 도메인 밖 접근에
# 기본 페이지가 응답한다. 첫 교체 때 원본을 한 번만 남긴다.
if [ ! -f /etc/nginx/nginx.conf.masiton-orig ]; then
  cp -p /etc/nginx/nginx.conf /etc/nginx/nginx.conf.masiton-orig
fi
install -m 0644 "$STAGE/nginx.conf" "$NGINX_CONF"

# 직접 접속 구조에서는 proxy가 없으므로 기본값 127.0.0.1만 신뢰한다. 외부가
# 보낸 X-Forwarded-For를 신뢰하지 않도록 별도 proxy CIDR은 배포 입력으로만 허용한다.
{
  echo '# Generated by nginx-install.sh; do not edit on the instance.'
  echo 'real_ip_header X-Forwarded-For;'
  echo 'real_ip_recursive on;'
  trusted_cidrs="${NGINX_TRUSTED_PROXY_CIDRS:-127.0.0.1}"
  IFS=',' read -r -a trusted_proxy_cidrs <<< "$trusted_cidrs"
  for cidr in "${trusted_proxy_cidrs[@]}"; do
    [ -n "$cidr" ] || continue
    case "$cidr" in
      *[!0-9a-fA-F:./]*) echo "신뢰 proxy CIDR 형식이 잘못됐다: $cidr" >&2; exit 1 ;;
    esac
    printf 'set_real_ip_from %s;\n' "$cidr"
  done
} > "$REAL_IP_CONF"

nginx -t
systemctl daemon-reload
systemctl enable nginx >/dev/null
systemctl restart nginx
if [ "$(systemctl is-active nginx)" != "active" ]; then
  echo "Nginx 재시작이 active 상태로 확인되지 않았다." >&2
  exit 1
fi

bash "$STAGE/nginx-smoke.sh"

install -m 0644 "$STAGE/masiton-tls-renew.service" /etc/systemd/system/masiton-tls-renew.service
install -m 0644 "$STAGE/masiton-tls-renew.timer" /etc/systemd/system/masiton-tls-renew.timer
systemctl daemon-reload
systemctl enable --now masiton-tls-renew.timer >/dev/null

trap - ERR
rm -rf "$ROLLBACK_DIR"

echo "nginx: enabled=$(systemctl is-enabled nginx) active=$(systemctl is-active nginx)"
echo "timer: enabled=$(systemctl is-enabled masiton-tls-renew.timer) active=$(systemctl is-active masiton-tls-renew.timer)"
