import assert from 'node:assert/strict'
import test from 'node:test'
import { NATURAL_LANGUAGE_TAG_OPTIONS, decodeNaturalLanguageResult, formatNaturalLanguageAppliedConditions, isNaturalLanguageRetryAllowed, naturalLanguageFieldGuidance, naturalLanguageFieldLabel, naturalLanguageFiltersFromFormData, naturalLanguageRetryDelay, searchRestaurantsByNaturalLanguage, toggleNaturalLanguageTag } from './natural-language-search-api.ts'
const response = { interpretation: { status: 'APPLIED', appliedConditions: { query: null, district: '성동구', category: null, creatorId: 'opaque-id', tags: ['MENU_NAENGMYEON'] }, ignoredConditions: [], conflicts: [], parserVersion: 'P1' }, results: { items: [{ id: 'r-1', name: '냉면집', district: '성동구', category: '한식', visitedBy: [], remainingVisitedByCount: 0 }], page: { number: 1, size: 20, totalElements: 1, totalPages: 1, hasNext: false } } }; const filters = { query: null, district: null, category: null, creatorId: 'opaque-id', tags: [] }
test('정상 응답은 opaque Creator ID와 함께 안전하게 해석한다', () => assert.equal(decodeNaturalLanguageResult(response)?.interpretation.appliedConditions.creatorId, 'opaque-id'))
test('FAILED 빈 결과와 잘못된 응답을 구분한다', () => { assert.equal(decodeNaturalLanguageResult({}), null); const failed = structuredClone(response) as any; failed.interpretation.status = 'FAILED'; failed.interpretation.appliedConditions = { query: null, district: null, category: null, creatorId: null, tags: [] }; failed.results.items = []; assert.equal(decodeNaturalLanguageResult(failed)?.interpretation.status, 'FAILED') })
test('429와 일시 오류만 재시도를 허용한다', () => { assert.equal(isNaturalLanguageRetryAllowed({ kind: 'invalid', message: 'bad', fieldGuidance: [] }), false); assert.equal(isNaturalLanguageRetryAllowed({ kind: 'rateLimited', message: 'slow', retryAvailableAt: null }), true); assert.equal(isNaturalLanguageRetryAllowed({ kind: 'error', message: 'server', retryAllowed: true }), true) })
test('요청은 기존 구조화 필터를 POST 본문에 보존한다', async () => { const previous = globalThis.fetch; let body = ''; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(response), { status: 200 }) }; try { const outcome = await searchRestaurantsByNaturalLanguage('성동구 냉면', filters); assert.equal(outcome.kind, 'success'); assert.deepEqual(JSON.parse(body).filters, filters) } finally { globalThis.fetch = previous } })
test('PARTIAL과 중첩된 잘못된 응답을 구분한다', () => { const partial = structuredClone(response) as any; partial.interpretation.status = 'PARTIAL'; partial.interpretation.ignoredConditions = [{ type: 'UNRESOLVED', text: '안전한 요약', reason: 'UNRESOLVED_VALUE' }]; assert.equal(decodeNaturalLanguageResult(partial)?.interpretation.status, 'PARTIAL'); partial.results.items[0].visitedBy = [{ id: 1, channelName: 'x' }]; assert.equal(decodeNaturalLanguageResult(partial), null) })
test('400은 재시도하지 않고 429·503·500은 계약 상태와 traceId를 보존한다', async () => { const previous = globalThis.fetch; const cases = [[400, 'invalid'], [429, 'rateLimited'], [503, 'unavailable'], [500, 'error']] as const; try { for (const [status, kind] of cases) { globalThis.fetch = async () => new Response(JSON.stringify({ message: 'm', traceId: 'trace-1' }), { status, headers: status === 429 ? { 'Retry-After': '30' } : undefined }); const outcome = await searchRestaurantsByNaturalLanguage('문장', filters, 2); assert.equal(outcome.kind, kind); assert.equal((outcome as { traceId?: string }).traceId, 'trace-1'); assert.equal(isNaturalLanguageRetryAllowed(outcome), status !== 400) } } finally { globalThis.fetch = previous } })
test('페이지 번호는 URL 대신 POST 본문으로 전달한다', async () => { const previous = globalThis.fetch; let body = ''; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(response), { status: 200 }) }; try { await searchRestaurantsByNaturalLanguage('문장', filters, 3); assert.equal(JSON.parse(body).page, 3) } finally { globalThis.fetch = previous } })
test('구조화 폼의 현재 편집값을 자연어 직접 필터로 정규화한다', () => { const data = new FormData(); data.set('query', '  냉면집  '); data.set('district', '성동구'); data.set('category', ''); data.set('creatorId', 'creator-live'); assert.deepEqual(naturalLanguageFiltersFromFormData(data, ['MENU_NAENGMYEON']), { query: '냉면집', district: '성동구', category: null, creatorId: 'creator-live', tags: ['MENU_NAENGMYEON'] }) })
test('적용 조건은 opaque ID와 태그 코드 대신 사용자용 이름을 표시한다', () => { assert.deepEqual(formatNaturalLanguageAppliedConditions(response.interpretation.appliedConditions, { 'opaque-id': '먹방연구소' }), ['자치구: 성동구', '유튜버: 먹방연구소', '태그: 냉면']); assert.deepEqual(formatNaturalLanguageAppliedConditions({ ...response.interpretation.appliedConditions, creatorId: 'unknown', tags: ['UNKNOWN'] }, {}), ['자치구: 성동구', '유튜버: 선택한 유튜버', '태그: 알 수 없는 태그']) })
test('같은 400도 오류 코드마다 다른 안내를 만든다', async () => { const previous = globalThis.fetch; const cases = [['NATURAL_LANGUAGE_EMPTY', []], ['INVALID_FIELD_VALUE', [{ field: 'filters.tags', reason: '최대 5개까지 허용합니다.' }]], ['INVALID_IDENTIFIER', [{ field: 'creatorId', reason: '식별자 형식이 올바르지 않습니다.' }]]] as const; const messages = new Set<string>(); try { for (const [code, errors] of cases) { globalThis.fetch = async () => new Response(JSON.stringify({ code, message: '요청 값을 확인해 주세요.', errors, traceId: 'trace-1' }), { status: 400 }); const outcome = await searchRestaurantsByNaturalLanguage('문장', filters); assert.equal(outcome.kind, 'invalid'); const invalid = outcome as { code?: string; message: string; fieldGuidance: Array<{ label: string; reason: string }> }; assert.equal(invalid.code, code); assert.equal(invalid.fieldGuidance.length, errors.length); messages.add(invalid.message) } assert.equal(messages.size, 3) } finally { globalThis.fetch = previous } })
test('필드 안내는 filters 접두사를 벗기고 사용자용 라벨을 쓴다', () => { assert.equal(naturalLanguageFieldLabel('filters.tags'), '태그'); assert.equal(naturalLanguageFieldLabel('creatorId'), '유튜버'); assert.equal(naturalLanguageFieldLabel('sentence'), '검색 문장'); assert.equal(naturalLanguageFieldLabel('unknownField'), 'unknownField'); assert.deepEqual(naturalLanguageFieldGuidance([{ field: 'filters.query', reason: '최대 100자까지 허용합니다.' }, { field: 'district' }, 'bad']), [{ label: '이름', reason: '최대 100자까지 허용합니다.' }]) })
test('알 수 없는 400 코드는 서버 메시지를 그대로 쓴다', async () => { const previous = globalThis.fetch; try { globalThis.fetch = async () => new Response(JSON.stringify({ code: 'UNMAPPED_CODE', message: '서버 문구', errors: [] }), { status: 400 }); const outcome = await searchRestaurantsByNaturalLanguage('문장', filters); assert.equal(outcome.kind === 'invalid' && outcome.message, '서버 문구') } finally { globalThis.fetch = previous } })
test('직접 태그 선택지는 코드마다 표시 라벨을 갖는다', () => { assert.ok(NATURAL_LANGUAGE_TAG_OPTIONS.length > 0); assert.ok(NATURAL_LANGUAGE_TAG_OPTIONS.every((option) => option.label.trim() && option.label !== option.code)); assert.deepEqual(NATURAL_LANGUAGE_TAG_OPTIONS.find((option) => option.code === 'MENU_NAENGMYEON'), { code: 'MENU_NAENGMYEON', label: '냉면' }) })
test('직접 태그 선택은 해제를 허용하고 계약 상한을 넘지 않는다', () => { assert.deepEqual(toggleNaturalLanguageTag([], 'MENU_RAMEN'), ['MENU_RAMEN']); assert.deepEqual(toggleNaturalLanguageTag(['MENU_RAMEN', 'TASTE_SPICY'], 'MENU_RAMEN'), ['TASTE_SPICY']); const full = ['MENU_RAMEN', 'MENU_SUSHI', 'MENU_PIZZA', 'TASTE_SPICY', 'TASTE_SWEET']; assert.deepEqual(toggleNaturalLanguageTag(full, 'OCCASION_SOLO'), full); assert.deepEqual(toggleNaturalLanguageTag(full, 'MENU_SUSHI'), ['MENU_RAMEN', 'MENU_PIZZA', 'TASTE_SPICY', 'TASTE_SWEET']) })
test('직접 태그가 선택되면 자연어 요청 본문의 filters.tags가 비어 있지 않다', async () => { const previous = globalThis.fetch; let body = ''; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(response), { status: 200 }) }; try { await searchRestaurantsByNaturalLanguage('성동구 냉면', { ...filters, tags: ['MENU_NAENGMYEON'] }); assert.deepEqual(JSON.parse(body).filters.tags, ['MENU_NAENGMYEON']) } finally { globalThis.fetch = previous } })
test('429 재시도 대기는 요청 시작이 아니라 응답 기준 남은 시간만 사용한다', () => { assert.equal(naturalLanguageRetryDelay(15_000, 5_000), 10_000); assert.equal(naturalLanguageRetryDelay(5_000, 6_000), 0) })
