import assert from 'node:assert/strict'
import test from 'node:test'
import { decodeNaturalLanguageResult, isNaturalLanguageRetryAllowed, naturalLanguageFiltersFromFormData, searchRestaurantsByNaturalLanguage } from './natural-language-search-api.ts'
const response = { interpretation: { status: 'APPLIED', appliedConditions: { query: null, district: '성동구', category: null, creatorId: 'opaque-id', tags: ['MENU_NAENGMYEON'] }, ignoredConditions: [], conflicts: [], parserVersion: 'P1' }, results: { items: [{ id: 'r-1', name: '냉면집', district: '성동구', category: '한식', visitedBy: [], remainingVisitedByCount: 0 }], page: { number: 1, size: 20, totalElements: 1, totalPages: 1, hasNext: false } } }; const filters = { query: null, district: null, category: null, creatorId: 'opaque-id', tags: [] }
test('정상 응답은 opaque Creator ID와 함께 안전하게 해석한다', () => assert.equal(decodeNaturalLanguageResult(response)?.interpretation.appliedConditions.creatorId, 'opaque-id'))
test('FAILED 빈 결과와 잘못된 응답을 구분한다', () => { assert.equal(decodeNaturalLanguageResult({}), null); const failed = structuredClone(response) as any; failed.interpretation.status = 'FAILED'; failed.interpretation.appliedConditions = { query: null, district: null, category: null, creatorId: null, tags: [] }; failed.results.items = []; assert.equal(decodeNaturalLanguageResult(failed)?.interpretation.status, 'FAILED') })
test('429와 일시 오류만 재시도를 허용한다', () => { assert.equal(isNaturalLanguageRetryAllowed({ kind: 'invalid', message: 'bad' }), false); assert.equal(isNaturalLanguageRetryAllowed({ kind: 'rateLimited', message: 'slow', retryAvailableAt: null }), true); assert.equal(isNaturalLanguageRetryAllowed({ kind: 'error', message: 'server', retryAllowed: true }), true) })
test('요청은 기존 구조화 필터를 POST 본문에 보존한다', async () => { const previous = globalThis.fetch; let body = ''; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(response), { status: 200 }) }; try { const outcome = await searchRestaurantsByNaturalLanguage('성동구 냉면', filters); assert.equal(outcome.kind, 'success'); assert.deepEqual(JSON.parse(body).filters, filters) } finally { globalThis.fetch = previous } })
test('PARTIAL과 중첩된 잘못된 응답을 구분한다', () => { const partial = structuredClone(response) as any; partial.interpretation.status = 'PARTIAL'; partial.interpretation.ignoredConditions = [{ type: 'UNRESOLVED', text: '안전한 요약', reason: 'UNRESOLVED_VALUE' }]; assert.equal(decodeNaturalLanguageResult(partial)?.interpretation.status, 'PARTIAL'); partial.results.items[0].visitedBy = [{ id: 1, channelName: 'x' }]; assert.equal(decodeNaturalLanguageResult(partial), null) })
test('400은 재시도하지 않고 429·503·500은 계약 상태와 traceId를 보존한다', async () => { const previous = globalThis.fetch; const cases = [[400, 'invalid'], [429, 'rateLimited'], [503, 'unavailable'], [500, 'error']] as const; try { for (const [status, kind] of cases) { globalThis.fetch = async () => new Response(JSON.stringify({ message: 'm', traceId: 'trace-1' }), { status, headers: status === 429 ? { 'Retry-After': '30' } : undefined }); const outcome = await searchRestaurantsByNaturalLanguage('문장', filters, 2); assert.equal(outcome.kind, kind); assert.equal((outcome as { traceId?: string }).traceId, 'trace-1'); assert.equal(isNaturalLanguageRetryAllowed(outcome), status !== 400) } } finally { globalThis.fetch = previous } })
test('페이지 번호는 URL 대신 POST 본문으로 전달한다', async () => { const previous = globalThis.fetch; let body = ''; globalThis.fetch = async (_input, init) => { body = String(init?.body); return new Response(JSON.stringify(response), { status: 200 }) }; try { await searchRestaurantsByNaturalLanguage('문장', filters, 3); assert.equal(JSON.parse(body).page, 3) } finally { globalThis.fetch = previous } })
test('구조화 폼의 현재 편집값을 자연어 직접 필터로 정규화한다', () => { const data = new FormData(); data.set('query', '  냉면집  '); data.set('district', '성동구'); data.set('category', ''); data.set('creatorId', 'creator-live'); assert.deepEqual(naturalLanguageFiltersFromFormData(data, ['MENU_NAENGMYEON']), { query: '냉면집', district: '성동구', category: null, creatorId: 'creator-live', tags: ['MENU_NAENGMYEON'] }) })
